### ISSUE TITLE
Support for rewriting CSS-URLs

### ISSUE THREAD

**Issue by thasmo** [fmal/gulp-inline-source#22]
It would be awesome if urls in stylesheets would be rewritten when embedded.

```css
.div {
  background: url('../images/background.jpg');
}
```
should become
```css
.div {
  background: url('static/images/background.jpg');
}
```

This probably needs a new config option to define the path to use for rewriting.
